# Generated by Django 4.1.4 on 2022-12-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('facebook', models.BooleanField(default=True)),
                ('twitter', models.BooleanField(default=True)),
                ('instagram', models.BooleanField(default=True)),
            ],
        ),
    ]
