# Generated by Django 4.1.4 on 2022-12-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='cover_art',
            field=models.ImageField(default='cover-art.png', upload_to=''),
        ),
    ]
