# Generated by Django 4.1.4 on 2022-12-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='facebook_handle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='instagram_handle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='tiktok_handle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='twitter_handle',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
