# Generated by Django 4.1.4 on 2022-12-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EXECUTIVE', 'Executive'), ('MANAGER', 'Manager'), ('ARTIST', 'Artist')], max_length=50),
        ),
    ]
