# Generated by Django 4.1.4 on 2022-12-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover_art',
            field=models.ImageField(default='cover_art.png', upload_to=''),
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover_art', models.ImageField(default='cover_art.png', upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('songs', models.ManyToManyField(to='content.song')),
            ],
        ),
    ]
